services:
  mosquitto:
   build: ./mosquitto 
   ports:
       - "1883:1883"
   container_name: 
    mosquitto-broker

  backend:
   build: ./backend
   ports:
     - "3000:3000"
     - "3002:3002"
     - "3003:3003"
   depends_on:
     - mosquitto
   container_name: 
    API-gateway
   volumes:
     - ./backend:/usr/src/app
  
  frontend:
   build: ./frontend
   ports:
     - "3001:3001"
   container_name: 
     frontend
   volumes:
     - ./frontend:/usr/src/app