services:
  mosquitto:
   build: ./mosquitto 
   ports:
       - "1883:1883"
   container_name: 
    mosquitto-broker

  backend:
   build: ./backend
   ports:
     - "3000:3000"
     - "3002:3002"
     - "3003:3003"
   depends_on:
     - mosquitto
   container_name: 
    tp-distribuidos
   volumes:
     - ./backend:/usr/src/app