services:
  mosquitto:
    build: ./mosquitto
	ports:
		- "1883":"1883"

backend:
   build: ./backend
   ports:
     - "3000:3000"
   depends_on:
    	mosquitto
   volumes:
     - ./backend:/usr/src/app